# Generated by Django 3.2.7 on 2021-09-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='creator_id_id',
            new_name='creator_id',
        ),
    ]
