# Generated by Django 3.2.7 on 2021-10-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidding_id',
            new_name='bidding_product',
        ),
    ]
