# Generated by Django 3.2.7 on 2021-10-01 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_creator_id_listing_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerId', to=settings.AUTH_USER_MODEL),
        ),
    ]
