# Generated by Django 3.2.7 on 2021-10-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_owner_id_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
