# Generated by Django 3.2.7 on 2021-10-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_images_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
