# Generated by Django 3.2.7 on 2021-10-06 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_owner_id_listing_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
