# Generated by Django 3.2.7 on 2021-10-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20211009_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='highest_bidder_id',
            new_name='bidder_id',
        ),
    ]
