# Generated by Django 3.2.7 on 2021-10-10 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_remove_bid_highest_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder_id',
            new_name='bidder',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
