# Generated by Django 3.2.7 on 2021-10-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20211010_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidding_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
