# Generated by Django 3.2.7 on 2021-10-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_bid_bidding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
        ),
    ]
