# Generated by Django 3.2.7 on 2021-10-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_rename_highest_bid_listing_highest_bidder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='winner_id',
            new_name='winner',
        ),
    ]
