# Generated by Django 3.2.7 on 2021-10-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_alter_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_id',
            new_name='commenter',
        ),
    ]
