# Generated by Django 3.2.7 on 2021-10-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_alter_listing_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True)),
            ],
        ),
    ]
